### PR TITLE
Added Countdown Timer

### PR DESCRIPTION
**Pull request by im-adithya**

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Great. I will suggest a few things

- [ ] Add a readme file having the description of this project and how to set up the project.
- [ ] Add screenshots of the page in the readme.

**Review by bislara — APPROVED** [review]
Great. Good job

**Comment by bislara** [comment]
@all-contributors please add @im-adithya for code, doc

**Comment by im-adithya** [comment]
> @all-contributors please add @im-adithya for code, doc 

Thank you so much! I learned a lot from this!

**Comment by bislara** [comment]
> Thank you so much! I learned a lot from this!

Great.  Felt good to know that.
Keep Learning 🙌

**Pull request merged**
