### PR TITLE
183 english dictionary

### LINKED ISSUE #183: English Dictionary
## Description
Make an application for dictionary feature which will fetch the meaning of a word. 

You can make a GUI for this or make it CLI based.

## Technologies and Languages

- Python
- javascript

Any other language and technology is welcomed.

### PR DESCRIPTION
**Pull request by gill876**
# English Dictionary

This is a simple CLI interface that defines English words from a csv file or from an API. One can use the local csv file to define words or have the option to check the csv but get the API if the word cannot be found in the csv files. More information on this is in the README.md.

Fixed #183 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

Screenshot from 2020-10-19 07-04-50
Screenshot from 2020-10-19 07-04-22

### CODE REVIEW

**Review by bislara — APPROVED** [review]
Great awesome.. Can you do one thing?

Add the screenshot (attached in the PR description ) also in the readme of the project

**Comment by gill876** [comment]
> Great awesome.. Can you do one thing?
> 
> Add the screenshot (attached in the PR description ) also in the readme of the project 

Thank you! Are the screenshots and README.md not enough in the folder? 😅

**Comment by bislara** [comment]
> Thank you! Are the screenshots and README.md not enough in the folder? 😅

Hey @gill876, I wanted u to add image in the readme so that people can see one example of the output.

**Comment by gill876** [comment]
> > Thank you! Are the screenshots and README.md not enough in the folder? sweat_smile
> 
> Hey @gill876, I wanted u to add image in the readme so that people can see one example of the output.

Done!

**Review by bislara — APPROVED** [review]
Wonderful. Good job. 
Happy Learning and Hacking 🤟✌

**Comment by bislara** [comment]
@all-contributors please add gill876 for code, doc

**Pull request merged**
