### PR TITLE
Card Slider 

### PR DESCRIPTION
**Pull request by ritviksharma3**
Screenshot Of Card Slider

I have fixed the Card Slider Issue. Also, added a screenshot with the same for better reference. 

- The card slider is capable to hold images.

- Swipe to move between cards.

- Add Links and Content to the Card.

- It is Mobile Responsive. 

Please let me know, if you want to make any changes.

### CODE REVIEW

**Comment by bislara** [comment]
Hey, @ritviksharma3  Good job. 
One doubt, Can some text be also added to the card?

**Comment by ritviksharma3** [comment]
@bislara Sure, will get it done soon.

**Comment by ritviksharma3** [comment]
@bislara Please review. I have made the changes.

**Review by bislara — APPROVED** [review]
Good job

**Comment by bislara** [comment]
@all-contributors please add ritviksharma3 for code, doc

**Pull request merged**
