### PR TITLE
140 leaked passwords

### PR DESCRIPTION
**Pull request by peteruche21**
# Description

created a the base pswpwner program

Fixed #(140)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Wonderful job with the code bro. Just I will suggest a few changes:-

- [ ] Add screenshots of your output in the readme of your project. 
- [ ] Add a requirements.txt file so that one can easily download the dependencies.
- [ ] Write the steps to run the file in the readme.

Good job for commenting the code.

**Comment by peteruche21** [comment]
the documentation is better explained

**Review by bislara — APPROVED** [review]
Perfect. Good job 

Happy Hacking and Learning ✌💪

**Comment by bislara** [comment]
@all-contributors please add peteruche21 for code, doc

**Pull request merged**
