### PR TITLE
Email Id extractor 

### LINKED ISSUE #27: Email Id extractor
## Description
Extract email addresses from the text given in the input and display all the email ids in the end

## Technologies and Languages
- Python
- Javascript
- C++
- Regex

You can use any other language or technologies as well.

## Aditional Work 
You can make a GUI for this application.

### PR DESCRIPTION
**Pull request by kamil200**
I made an email extractor using python.

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #27

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

email_extarctor1
 I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
Well done with the code bro 🤟✌

**Review by bislara — APPROVED** [review]
Perfectly done

**Comment by bislara** [comment]
@all-contributors please add kamil200 for code, doc

**Comment by kamil200** [comment]
@bislara thank you brother!
happy to hear that
looking forward to contribute again

**Pull request merged**
