### PR TITLE
Updated Readme For Both 

### PR DESCRIPTION
**Pull request by TestPrab**

### CODE REVIEW

**Comment by TestPrab** [comment]
@bislara  I have updated the readme but I noticed that by mistake I have added Image Cartoonizer file in Invisible Cloak..if possible please remove it from there I have added another copy of it directy in Python directory..

**Comment by bislara** [comment]
Okay fine. Better u can make a commit deleting those files from the Invisible Cloak folder

**Comment by TestPrab** [comment]
Okay i have removed it and made the commit please check once

**Review by bislara — APPROVED** [review]
Perfect. Thanks a lot.

**Pull request merged**
