### PR TITLE
Add event timeline

### LINKED ISSUE #180: Event Timeline
## Description
Make an attractive timeline for an event, project, etc

## Technologies and Languages

- HTML, CSS, Javascript

### PR DESCRIPTION
**Pull request by senguyen1011**
# Description

Created an event timeline app. Allows users to input events and creates a timeline from those inputs. Bootstrapped by React, use `npm start` to run the app locally.
image

Fixed #180 

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [X ] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
Hey @senguyen1011  Put this in the web Hacks folder please. then I will review

**Comment by senguyen1011** [comment]
Moved to Web Hacks.

**Review by bislara — CHANGES_REQUESTED** [review]
Wonderful bro loved it.
Just a few changes that I will suggest.

- [ ] In the readme, add a screenshot, of how the application is looking
- [ ] You forgot to delete it from the Javascript folder 😅
- [ ] In the readme, write a little bit more how to set up and run the file so that a newbie can also test this application

**Review by bislara — APPROVED** [review]
Well done. Good job

**Comment by bislara** [comment]
@all-contributors please add senguyen1011 for code, doc

**Pull request merged**
