### PR TITLE
Feature/sens sms

### LINKED ISSUE #76: Send SMS
## Description
Script to send SMS to a given number taken as input from the user.

## Technologies and Languages

- Python 
- Javascript

Any other language and technology are also fine.

## Aditional Work 
Make a GUI for this application

### PR DESCRIPTION
**Pull request by gs202**
# Description
Python Script to send SMS to a given number taken as input from the user using Twilio.
The script validates the number before sending the SMS

Dependencies:
Twilio
phonenumbers

Fixed #76 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
hey @gs202  Good job. Just add one thing

- [ ] Attach screenshot of the output both in the readme as well as in PR description

**Comment by gs202** [comment]
Screenshot was added

**Review by bislara — APPROVED** [review]
Perfect

**Comment by bislara** [comment]
@all-contributors please add gs202 for code, doc

**Pull request merged**
