### PR TITLE
155 folder restructure

### PR DESCRIPTION
**Pull request by TestPrab**
Fixed issue #155  created two folder one for python and one for JS and added readme in  both of them with a proper tabulated form

### CODE REVIEW

**Comment by TestPrab** [comment]
just one thing can you please merge this PR so that the Links for the projects are changed and I will add it accordingly

**Comment by bislara** [comment]
Okay okay sure

**Comment by bislara** [comment]
@all-contributors please add TestPrab for tool, doc

**Comment by bislara** [comment]
@TestPrab  Done. Check it out.

**Comment by TestPrab** [comment]
yes thanks I am creating the readme file with the links

**Pull request merged**
