### PR TITLE
Added rules

### LINKED ISSUE #33: Normalize the syntax and create rules for future commits
## Description
Currently, there are no rules that define how the code is to be formatted as well as the format of the directory. This should be changed to improve the structure

The structure can be like this
- [language]
  - [project]
    - [files]

Also, there can be a specific definition for each language formatting, Like using Black for Python, Google Style for Java and Cpp, and so on

## Technologies and Languages
None

### PR DESCRIPTION
**Pull request by UbadahJ**
# Description

Here a draft for rules

Fixes #33 

## Type of change

- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by UbadahJ** [comment]
@bislara Please review the changes. For a better look, directly check the fork with branch Rules

**Comment by bislara** [comment]
Wonderful job bro. But can you please wait for some time? Let the pending PRs get merged. It will be better if we do this after that. Sounds good?

**Comment by UbadahJ** [comment]
Sure, but add a link to README so the following PRs follow the conventions

**Comment by bislara** [comment]
Bro, Link to which file you meant ?

**Comment by bislara** [comment]
Oh Okay bro.

**Pull request closed without merging**
