### PR TITLE
Password strength checker

### PR DESCRIPTION
**Pull request by CodeSadhu**
## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

## Screenshot:
Output

### CODE REVIEW

**Comment by bislara** [comment]
There are a few changes that I will be suggesting.

- [ ]  Do attach screenshots of your output in the readme as well as in the PR comment

Good job with the code. 👍

**Comment by CodeSadhu** [comment]
@bislara Thanks for the compliments 😉  Should I be making one more PR with the screenshots added in the README?

**Comment by bislara** [comment]
no, do it in this PR itself.

**Comment by CodeSadhu** [comment]
@bislara Okay cool!

**Comment by CodeSadhu** [comment]
@bislara Please review. Changes made.

**Comment by CodeSadhu** [comment]
@bislara Done 😄

**Review by bislara — APPROVED** [review]
perfect

**Comment by bislara** [comment]
@all-contributors please add CodeSadhu for code, doc

**Comment by CodeSadhu** [comment]
@bislara Hey the rules for Hacktoberfest have been updated. You need to add a label **hacktoberfest-accepted** to merged PRs now. Check this https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by bislara** [comment]
Yes, I have seen this. Was going to add. bdw PRs merged before 3 October will still be accepted. There won't be any issue in it. 

Thanks for sharing.

**Comment by CodeSadhu** [comment]
@bislara Cool thanks!

**Pull request merged**
