### PR TITLE
CLI Based Encode and Decode Tool

### LINKED ISSUE #157: Encryption Tool
## Description
A python tool with which you can encrypt plain text into some famous algorithms and cipher such as: Morse, Base64, Hex, Caesar Cipher and etc.

## Technologies and Languages
List of all the technologies and languages which you think are required for solving this issue:
* Python
* Base64 Module
* binascii Module

## Notes
I've made already this project and thought about contributing it here, and so you can check out the project right there: [Project](https://github.com/maxily1/Encrpytion-Tool)
Sadly, it is unable to decrypt yet, but will be added ASAP.

### PR DESCRIPTION
**Pull request by maxily1**
# Description

I've added an Encode and Decode tool in Python using in CLI.

Fixed #157

## Type of change

_Please delete options that are not relevant._
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by maxily1** [comment]
@bislara Hey could you take a look at this?

**Comment by bislara** [comment]
Hey, Can you also attach screenshots of the output in the readme. 
Also, anything with the decrypt part?

**Comment by maxily1** [comment]
Decrypt part is added, It's buggy currently (Caesar Cipher only), and I am actively working on a fix. 
I'll add a screenshot and a requirements.

**Comment by maxily1** [comment]
Could you please accept this PR for Hacktoberfest (It's better than waiting until I'll finish the fix) and I'll constantly fix the errors, add requirements.txt?

**Comment by bislara** [comment]
@maxily1  I guess the review period would have started now. So don't worry about Hacktoberfest. 🤟🙂

**Comment by maxily1** [comment]
Hey, Just a few final touches and I am pushing it.

**Comment by maxily1** [comment]
Hey @bislara , Sorry for the excessive push and spam.
I was having trouble getting the screenshots to work as I am new to Markdown. 
All your requirements were completed.

**Comment by bislara** [comment]
Great. Is the decrypt thing working?

**Comment by maxily1** [comment]
Yes it is! You're invited to test it!

**Comment by bislara** [comment]
Wonderful. Also, add one screenshot in the readme for decrypt

**Comment by maxily1** [comment]
Will do rn

**Comment by maxily1** [comment]
Okay, Final change done.

**Review by bislara — APPROVED** [review]
Good Job

**Comment by bislara** [comment]
@all-contributors please add maxily1 for code, doc

**Pull request merged**
