### PR TITLE
Script to download audio from youtube videos

### LINKED ISSUE #1: AudioDownloader
## Project description
 To write a python Script which uses google API to search videos for the keyword and download the audio of the respective video using pafy library
 
 ## Relevant Technology
Python, Ideas about APIs
 
 ### Complexity
 * [x]  Beginner - This project requires no or little prior knowledge of the technologies specified to contribute to the project
 * [ ]  Intermediate - The user should have some prior knowledge of the technologies to the point where they know how to use it, 
 * [ ]  Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### PR DESCRIPTION
**Pull request by gudeliauskaspam**
- config.py file with settings and constants
- references to all codes and libraries used
- readme.md file that explains how to use the script
- Issue: AudioDownloader #1 

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #1

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Good Job. Just a few changes

- [x] Now the folder structure has changed. Pull from upstream, and then put your folder inside the python folder.
- [x] Add screenshot of your output in the readme. 
- [ ] In the readme, mention the steps to setup and run the file. Better add a requirements.txt file having the dependencies required to be installed for this application

**Comment by gudeliauskaspam** [comment]
All done!

**Review by bislara — APPROVED** [review]
Well Done. Good Job

**Comment by bislara** [comment]
@all-contributors please add gudeliauskaspam for code, doc

**Pull request merged**
