### PR TITLE
Adding image cartoonize code

### LINKED ISSUE #115: Image Cartoonizer
## Description
Convert an image to its cartoon version.

## Technologies and Languages

- Python
- Simple Image processing Techniques

## Aditional Work 
Make a GUI for this application

### PR DESCRIPTION
**Pull request by Frans06**
# Description

I added a new folder for the image cartoonizer problem. This is base on opencv and had a cli system with typer. What it does is Extrapolate a pyramid image to find colors and find contours. 

Fixed #115 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Great Wonderful job bro. It's perfect. Just a few changes:-

- [ ] its better if you can add a requirements.txt file, so that people can directly install all the dependencies and run the file.
- [ ] Write a proper description in the PR.

**Comment by Frans06** [comment]
@bislara I made the suggested changes.

**Review by bislara — APPROVED** [review]
Perfect

**Comment by bislara** [comment]
@all-contributors please add Frans06 for code, doc

**Pull request merged**
