### PR TITLE
Created Clock Application in python #182

### LINKED ISSUE #182: Clock Application
## Description
Make an application for clock having features like:-

- [ ] Show the current time
- [ ] Stop watch 
- [ ] Timer

It's better if you can make a simple GUI for this

## Technologies and Languages

- Python
- Javascript

Any other language and technology is also welcomed.

### PR DESCRIPTION
**Pull request by luccas13**
**Description**

Problem solved clock application in python.

Fixed #182

**Type of change**

- [ ] New feature
- [ ] Documentation Update

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added screenshots that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Hey well-done bro. 
Just a few changes

- [ ] add the screenshot in the readme
- [ ] write more details about the application in the readme

Rest seems awesome.

**Comment by luccas13** [comment]
I already added the changes, I hope everything is ok! :)

**Review by bislara — APPROVED** [review]
Great. Good job

**Comment by bislara** [comment]
@all-contributors please add @luccas13 for code, doc

**Comment by luccas13** [comment]
Hi!
If I want to optimize the code, should I create an Issue first?

**Comment by bislara** [comment]
Yup.

**Pull request merged**
