### PR TITLE
added ping pong game #143

### LINKED ISSUE #143: Ping Pong Game using turtle module
## Description
@bislara Could you please assign me the task of adding in this mini-project.

## Technologies and Languages
Python
Turtle (python module)

### PR DESCRIPTION
**Pull request by Lakshita2002**
# Description

Added in a new folder "Ping_Pong_Game"

Fixed #143

## Type of change

Added in 4 files in the folder "Ping_Pong_Game"

## Checklist:

- [👍  ] My code follows the style guidelines(Clean Code) of this project
- [👍  ] I have performed a self-review of my own code
- [👍  ] I have commented my code, particularly in hard-to-understand areas
- [👍  ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [👍  ] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Wonderful job. Well done. Happy to see people utilizing the lockdown time in a proper way.

Just one suggestion. 

- [ ] Add a requirements.txt file inside your project folder. 
This will help the user to directly download all the required dependencies.

**Comment by Lakshita2002** [comment]
@bislara Took me a while to figure out what a requirements.txt file meant. I've added the same.

**Comment by bislara** [comment]
> @bislara Took me a while to figure out what a requirements.txt file meant. I've added the same.

Sorry, I should have mentioned more clearly maybe. Well good that u figured it out.

**Review by bislara — APPROVED** [review]
Perfect. 
Happy hacking and learning ✌🤟

**Comment by bislara** [comment]
@all-contributors please add Lakshita2002 for code, doc

**Comment by Lakshita2002** [comment]
@bislara It's alright. I would have commented for sure if I faced any problems. Happy Learning! 🎉

**Pull request merged**
