### PR TITLE
Added Pdf_Reader folder having pdf_reader GUI and normal script #8

### PR DESCRIPTION
**Pull request by devil-cyber**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
There are a few changes that I will be suggesting.

- [ ] Write a proper description in the PR 
- [ ]  Add a readme file inside your project folder. Add the description of the project in that file.
- [ ]  Do attach screenshots of your output in the readme as well as in the PR comment

Good job with the code. 👍

**Comment by devil-cyber** [comment]
Ok I will do that

**Comment by devil-cyber** [comment]
Take a look I have added a readme file.
Take a look at [screenshot](https://drive.google.com/file/d/17uGLUsJaDmzLTuCJF1thyjNUt5cV3r8o/view?usp=sharing)

**Comment by bislara** [comment]
@all-contributors please add devil-cyber for code, doc

**Comment by bislara** [comment]
@all-contributors please add @devil-cyber for code, doc

**Pull request merged**
