### PR TITLE
Added OCR

### PR DESCRIPTION
**Pull request by Samikdevel**
# Description

Added the ocr application

Fixed #(#38 )

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have included a screenshot
Screenshot

### CODE REVIEW

**Comment by bislara** [comment]
Great. good job with the code. I will suggest a change.

- [ ] Add images of the output in the readme as well as in PR. put the images inside the project folder

**Comment by Samikdevel** [comment]
Done

**Review by bislara — APPROVED** [review]
Perfect

**Comment by bislara** [comment]
@all-contributors please add Samikdevel for code, doc

**Pull request merged**
