### PR TITLE
Issue #116 Quiz App

### PR DESCRIPTION
**Pull request by Atharva8**
# Description

This is an quiz app made in python using tkinter, Which reads a csv file containing questions and their answers for the same.

Fixed #(116)

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
wonderful job. I had a query. On starting the app, it will load a question and on clicking on any ans, it will show if it's correct or not and then show the next question. and in the end, it will show the score. 
I am right in this flow? or it's little different than this?

**Comment by Atharva8** [comment]
Thank you, yes the flow is the same as mentioned except is does not show if the answer is right or wrong and only shows the score at the end.

**Comment by bislara** [comment]
Can we add that user can know which question is wrong? Maybe after answering that question or at the end we can show which questions are wrong.

**Comment by Atharva8** [comment]
Yes Sure, Will start working on it

**Comment by Atharva8** [comment]
Hi  I have made the necessary changes to the code and the program now shows the wrong questions answered and also shows their solutions, as shown in the readme. Thanks

**Review by bislara — APPROVED** [review]
Wow. Awesome bro.

Happy Hacking and Learning. 🤟✌

**Comment by bislara** [comment]
@all-contributors please add Atharva8 for code, doc

**Pull request merged**
