### PR TITLE
Js-anim

### LINKED ISSUE #172: JS Animations
## Description
Add the code for different types of animations. 
Make a simple page showing the animation
IMP - Do comment in the issue which type of animation u want to show.

## Technologies and Languages
- Javascript

Any other language and technology is welcomed

### PR DESCRIPTION
**Pull request by m4dummies**
# Java script animation

The script portrays a 3D animation made in javascript

Fixed #172 

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by m4dummies** [comment]
Hi @bislara , can you help me with this error. I dont really know why it didn't pass the script works.

**Comment by m4dummies** [comment]
Theres no error in the script but i failed one of the checks, 'greetings'. How do i fix that @bislara ?

**Comment by bislara** [comment]
No no that's fine. That's the greeting bot for the first time contributors. There is some issue with that..leave it. 
Can you just do one thing? Please add a small gif showing the animation in the readme

It will help others to know better whats the animation is all about.

**Comment by m4dummies** [comment]
Ok sure ill add a gif :)

**Comment by m4dummies** [comment]
@bislara I added the GIF can you check and let me know if it works?

**Review by bislara — APPROVED** [review]
WOW, it looks so amazing. Well done

Keep Learning!

**Comment by bislara** [comment]
@all-contributors please add m4dummies for code, doc

**Pull request merged**
