### PR TITLE
Find website broken links

### LINKED ISSUE #118: Find Broken Links
## Description
Find all the broken links of a website.
Take the link of the website as the input from the user

## Technologies and Languages

- Python
- Javascript

Any other language and technology is also welcome

## Aditional Work 
Make a GUI for this application

### PR DESCRIPTION
**Pull request by cyrilico**
# Description

This PR implements the functionality of detecting broken links withing a website, both in anchor and image elements.

Closes #118 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Wonderful job. 
Can you just add one thing?

- [ ] Add the screenshot in the readme as well

**Comment by cyrilico** [comment]
All set

**Review by bislara — APPROVED** [review]
Perfect

**Comment by bislara** [comment]
@all-contributors please add cyrilico for code, doc

**Pull request merged**
