### PR TITLE
Added Wifi Password Getter Hack

### PR DESCRIPTION
**Pull request by harshit-saraswat**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
-Added Wifi Hack Script and GUI to fetch all stored wifi connections and passwords.

Fixed #(20)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
Wonderful job bro. Well done with the code.

Just one change 

- [ ] add a readme inside the project folder with the project description in it

**Comment by harshit-saraswat** [comment]
> Wonderful job bro. Well done with the code.
> 
> Just one change
> 
> * [x]  add a readme inside the project folder with the project description in it

Hey, just added readme. Can you check it now?

**Review by bislara — APPROVED** [review]
Perfect. well done

**Comment by bislara** [comment]
@all-contributors please add harshit-saraswat for code, doc

**Comment by bislara** [comment]
@all-contributors please add @harshit-saraswat for code, doc

**Pull request merged**
