### PR TITLE
Feature/OTP generator

### LINKED ISSUE #78: Suggestion: OTP generating script that paste it into the clipboard
## Description
Small script that generates OTP from an auth key and paste it into the clipboard.
This is useful when you have MFA in your phone and you'd like to automate the flow 

## Technologies and Languages
Python

## Aditional Work 
I'd like to do it :)

### PR DESCRIPTION
**Pull request by gs202**
# Description

Python Script to generate OTP code and paste it into your clipboard.

Dependencies:
pyotp

Fixed #78 

## Type of change

_Please delete options that are not relevant._

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
hey @gs202 Good job. Just add one thing

- [ ]  Attach screenshot of the output both in the readme as well as in PR description

**Comment by gs202** [comment]
> hey @gs202 Good job. Just add one thing
> 
> * [ ]   Attach screenshot of the output both in the readme as well as in PR description

The output is just a 6 digits code that is copied to the clipboard, I'm not sure that a screenshot can demonstrate it

**Comment by bislara** [comment]
you can show the clipboard in word, excel etc.  [Try this ](https://www.dummies.com/software/microsoft-office/word/how-to-view-the-clipboard-in-word-2016/)

**Review by bislara — APPROVED** [review]
Perfect

**Comment by bislara** [comment]
@all-contributors please add gs202 for code, doc

**Pull request merged**
