### PR TITLE
210 angry birds game

### LINKED ISSUE #210: Angry Birds Game
## Description
Write codes for Angry Bird Game

## Technologies and Languages

- Python

Feel free to use any other language and technology

### PR DESCRIPTION
**Pull request by hemil26**
# Description

Created a Angry Birds game in python using pygames.

Fixed #210 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
The images in the readme are not getting loaded. Could you please check that

**Comment by hemil26** [comment]
@bislara yes I'll check it out!

**Comment by hemil26** [comment]
@bislara fixed the readme.md issue check it out.

**Review by bislara — APPROVED** [review]
Awesome. Well done 
Happy coding 🚀🎉🙌

**Comment by bislara** [comment]
@all-contributors please add @hemil26 for code, doc

**Pull request merged**
