### PR TITLE
Implemented a Paint App in Python using PyQt5

### PR DESCRIPTION
**Pull request by pranav6670**
# Description

Made a Paint application using PyQt5. 

Fixed #(6)

## Type of change

_Please delete options that are not relevant._

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by pranav6670** [comment]
Please check my PR @bislara. Thank You!

**Comment by bislara** [comment]
Well done with the code bro. 🤟✌

**Review by bislara — APPROVED** [review]
Completed the project

**Comment by pranav6670** [comment]
> Completed the project

Thank you for the opportunity! Should I delete the branch?

**Comment by bislara** [comment]
Yes it's up to you

**Pull request merged**
