### PR TITLE
Hyperlink extractor

### LINKED ISSUE #28: Hyperlink Extractor
## Description
Extract any Link with either HTTP or HTTPS protocol from the text given in the input and display all the links in the end.

## Technologies and Languages
- Python
- Javascript
- C++
- Regex

You can use any other language or technologies as well.

## Aditional Work 
You can make a GUI for this application.

### PR DESCRIPTION
**Pull request by UbadahJ**
# Description

Add the HyperLink Extractor

Fixed #28 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
Good job with the code. 👍🤟

Just one thing. Can you attach screenshot of your output in the comment?

**Comment by bislara** [comment]
Also, it would be great if you could add screenshots in the readme inside your project folder.

**Comment by UbadahJ** [comment]
Sure (btw it is README as well)

cmd

gui

Also, should this be approved tomorrow to be counted in hacktoberfest?

**Comment by UbadahJ** [comment]
Sure (btw it is in README as well)

cmd

gui

Also, should this be approved tomorrow to be counted in hactoberfest?

**Comment by bislara** [comment]
Wow, that's great. Well done. 

Also, according to the hacktoberfest rule, 
"all pull requests created between Oct 1 and Oct 31 will count, regardless of when you register for Hacktoberfest. Pull requests created before Oct 1 but merged or marked as ready for review after do not count."

Should I merge it or you will create another one tomorrow?

**Comment by UbadahJ** [comment]
Can we until tomorrow to merge it?

**Comment by UbadahJ** [comment]
Or maybe I can take another issue to work on if that simplier

**Comment by bislara** [comment]
Sure no problem.

**Comment by bislara** [comment]
@UbadahJ  You can create another PR now and add these files

**Comment by bislara** [comment]
@UbadahJ  Put it inside proper folder ie Inside the python folder.

**Comment by bislara** [comment]
@UbadahJ Can you please put it inside the python folder.I will merge immediately after this

**Comment by UbadahJ** [comment]
@bislara Merged the latest upstream

**Review by bislara — APPROVED** [review]

**Comment by bislara** [comment]
@all-contributors please add @UbadahJ for code, doc

**Pull request merged**
