### PR TITLE
Screen Recorder 

### LINKED ISSUE #26: Screen Recorder
## Description
Design a screen recorder app (GUI with its backend) which can capture the screen and record the screen. 

## Technologies and Languages

- Python
- PyQt or Tkinter library 

## Aditional Work 
convert the app to an executable binary file

### PR DESCRIPTION
**Pull request by pgirikishore**
# Description

I have created a GUI using PyQt5 for Screen record and capture. 

Fixed #26 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added screenshots(if any) that prove my fix is effective or that my feature works

<a href="https://ibb.co/gjRBMs0">screenshot</a>

### CODE REVIEW

**Comment by bislara** [comment]
There are a few changes that I will be suggesting.

- [ ]  Add a readme file inside your project folder. Add the description of the project in that file.
- [ ]  Do attach screenshots of your output in the readme as well as in the PR comment

Good job with the code. 👍

**Comment by pgirikishore** [comment]
I'm done with the changes. You can review the code folder now

**Review by bislara — APPROVED** [review]
Looks fine

**Comment by bislara** [comment]
@all-contributors please add pgirikishore for code, doc

**Pull request merged**
