### PR TITLE
Pinging websites

### LINKED ISSUE #218: Pinging Script with a mailer.
## Description
A script that will continuously ping a server to see if the server is live or not and email the users of it is not live.

## Technologies and Languages
Python.

### PR DESCRIPTION
**Pull request by arnav-deep**
# Description

Added pinging-website, a script to automatically alert users when a server or website goes down.

Fixed #218

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Great. Awesome. 

Can you please add a few screenshots of your output in the readme? It will help to know more about the project.

**Comment by arnav-deep** [comment]
Hi @bislara 

I have added the screenshot. Can you tell me exactly why the check is failing? The code is running well in my local system.

**Comment by bislara** [comment]
hey @arnav-deep, there is no error in your code, actually, there is some problem with the greeting bot.  It has nothing to do with ur code. That bot just comments a greeting message for the first time contributors. 

Give me little time. I will check and merge it finally

**Review by bislara — COMMENTED** [review]
Awesome bro. Well done. 
Also, it's wonderful that u have commented the code so well. 

Keep Learning 🤟

**Comment by bislara** [comment]
@all-contributors please add @arnav-deep for code, doc

**Comment by arnav-deep** [comment]
@bislara Thanks

**Pull request merged**
