### PR TITLE
75 ipl score notifier

### LINKED ISSUE #75: IPL Score Notifier
## Description
Script that will give notification of the live score of the ongoing match. 

## Technologies and Languages

- Python

Any other language and technology is also fine

## Aditional Work 
Convert the application to an executable file which can run without installing the dependencies.

### PR DESCRIPTION
**Pull request by megabyte98**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #75

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by megabyte98** [comment]
test

**Review by bislara — CHANGES_REQUESTED** [review]
Wonderful job with the code. I just want few changes. 

- [ ]  Can we have toast notification or any other notifier for the latest score of the ongoing match
- [ ] Add a readme inside the project folder and attach screenshot in it as well.

**Comment by megabyte98** [comment]
sure I will add these changes and make a PR

**Comment by megabyte98** [comment]
I have done the requested  changes :)

**Review by bislara — APPROVED** [review]
Perfect

**Comment by bislara** [comment]
@all-contributors please add megabyte98 for code, doc

**Pull request merged**
