### PR TITLE
Scrap all email from the website link in python

### LINKED ISSUE #88: Scrap Emails
## Description
Scrap all email from the website link given as  input from the user

## Technologies and Languages

- python
- Javascript

Any other language and technology is also fine.

## Aditional Work 
Make a GUI for this application

### PR DESCRIPTION
**Pull request by ronanren**
# Description

it's a function to scraping emails in python from website link given as input from the user.
I used the library requests and re.

Fixed #88 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
Great. Wonderful job. 
Can we extend this a little bit? 

I was thinking if we could also scrap links of the same domain from the website and get emails from those links as well. 
Can you try this?

**Comment by ronanren** [comment]
Yes, i will try this

**Comment by bislara** [comment]
Great. let me know if you need any help.

**Review by bislara — APPROVED** [review]
Perfect

**Comment by bislara** [comment]
@all-contributors please add ronanren for code, doc

**Pull request merged**
