### PR TITLE
Phone number extractor

### LINKED ISSUE #29: Phone number Extractor
## Description
Extract all the 10 digit phone number from the text given in the input and display all the numbers at the end

## Technologies and Languages
- Python
- Javascript
- C++
- Regex

You can use any other language or technologies as well.

## Aditional Work 
You can make a GUI for this application.

### PR DESCRIPTION
**Pull request by DevanshD3**
# Description
I have coded the desired "phone number extractor"

Fixed #29 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
There are a few changes that I will be suggesting. 

- [ ] Kindly put your code inside a new folder and name the folder as the issue name.
- [ ] Add a readme file inside your project folder. Add the description of the project in that file.
- [ ] Do attach screenshots of your output. 

Good job with the code. 👍

**Comment by DevanshD3** [comment]
Sure sure ! Will do that!

**Comment by DevanshD3** [comment]
Hey @bislara I was having internal issues adding the output to the readme file. So i have added it to the folder itself. Hope you merge this PR

**Comment by bislara** [comment]
That's fine. No problem.

**Review by bislara — APPROVED** [review]
Completed the project correctly.

**Comment by bislara** [comment]
@all-contributors please add DevanshD3 for code, doc

**Pull request merged**
