### PR TITLE
Jpg to Png convertor #40

### PR DESCRIPTION
**Pull request by BatoolMM**
# Description

I created a new python script to convert the image from jpg to png.
It displays GUI using ipywidgets and Jupyter Notebook (using GoogleColab). I added README.md to explain how to run the notebook. I made comments using markdown in every step of the code. 

Please let me know if you need me to add/change anything.

### CODE REVIEW

**Comment by bislara** [comment]
Wonderful job bro. Well done.

Just one change 

- [ ] Add the code to show that the image is actually converted to png. Display the extension of the input image as well as the output image.

**Comment by BatoolMM** [comment]
I made some changes. The name of the image and its extension can be shown. Also, the image can be displayed before converting it to png.

**Review by bislara — APPROVED** [review]
Perfect

**Comment by bislara** [comment]
@all-contributors please add BatoolMM for code, doc

**Pull request merged**
