### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by prinsusinghal**
# Description

Fixed #(193)

## Type of change

_Please delete options that are not relevant._

- [ ] Made a completely new web app.

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by prinsusinghal** [comment]
GitGuardian Security Checks is failing because I have used Open Weather API key which is kind of a unique one (my personal one).

**Comment by bislara** [comment]
> GitGuardian Security Checks is failing because I have used Open Weather API key which is kind of a unique one (my personal one). There is as such no problem with the app.

Okay, no problem bro. Also, can u please add the steps to follow to get the key in the readme?

**Comment by prinsusinghal** [comment]
> > GitGuardian Security Checks is failing because I have used Open Weather API key which is kind of a unique one (my personal one). There is as such no problem with the app.
> 
> Okay, no problem bro. Also, can u please add the steps to follow to get the key in the readme?

Sure

**Comment by prinsusinghal** [comment]
User needs to create an account on https://openweathermap.org/ and then the user gets the API key.

**Comment by prinsusinghal** [comment]
@bislara I have added the steps to get API Key in README.md

**Review by bislara — APPROVED** [review]
Well done. Good job

**Comment by bislara** [comment]
@all-contributors please add prinsusinghal for code, doc

**Comment by prinsusinghal** [comment]
@bislara Please add "hacktoberfest-accepted" label to this.

**Comment by bislara** [comment]
Hey @prinsusinghal  My repo is already having hacktoberfest topic. So, this PR is automatically be considered for hacktoberfest. The review period would have already started for this PR. If there is still an issue. I am adding the hacktoberfest-accepted label to this PR. 🤟

**Pull request merged**
