### PR TITLE
113 pdf watermaker

### LINKED ISSUE #113: PDF Watermarker
## Description
Add watermark to every page of the PDF or to a specific page (ask the user to give the page number as input)

## Technologies and Languages

- Python

Any other language and technology are welcomed.

## Aditional Work 
Make a GUI for this

### PR DESCRIPTION
**Pull request by Frans06**
# Description

Using reportlab and PyPDF2 in order to add a watermark layer to a pdf.

Fixed #113 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
Wonderful job. Well done. 
Just one doubt.
Can we add the watermark in the background of the text? So that the text in the pdf can be visible.

**Comment by Frans06** [comment]
@bislara In order to make it easier for some pdfs with images, I added transparency to the watermark.

**Comment by bislara** [comment]
Perfect now. 
You have changed the image in the readme as well but have written original document beside it. Can you just update the image in the readme as well.

**Comment by Frans06** [comment]
@bislara Changes Made

**Review by 10smruti — APPROVED** [review]
Perfect. Well done.

Happy Hacking and Learning 🤟✌👍

**Pull request merged**
