### PR TITLE
 addidng covid_19

### LINKED ISSUE #153: Covid 19-gif
## Description
Wanted to plot the number of corona cases on the global map in .gif format

## Technologies and Languages
Technologies : Jupyter Notebook , DataVisualization
Languages :  Python 3.x

## Aditional Work 
Check the overview of my project [here](https://github.com/bunnysworld/c-19-gif)

### PR DESCRIPTION
**Pull request by bunnysworld**
# Description

- Summary
  - Simple Covid-19 visualization project 
  - plotted on the world map according to the no of Covid+ve cases country wise
- Requirements
  - all dependencies of the projects are in requirements.txt

Fixed #153 

## Type of change

_Please delete options that are not relevant.

- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Great. Awesome Bro.  Well done

Just a few changes I will suggest.
- [x]  Add python file (.py extension) for the map.ipynb file
- [x] Add a requirement.txt file having all the dependencies required for this project.
- [x] Update readme with proper instructions to setup and run the main file

**Comment by bunnysworld** [comment]
hey @bislara thanks for reviewing my PR . as requirement.txt  is already attached to my PR and rest i'll do.

**Review by bislara — APPROVED** [review]
Great. Well done.

**Comment by bislara** [comment]
@all-contributors please add bunnysworld for code, doc

**Pull request merged**
