### PR TITLE
CurrencyConverter via Python

### PR DESCRIPTION
**Pull request by vighneshdeepweb**
# Description

Python Script that Automates Currency Conversion via use of https://fixer.io to get the access token that basically helps in conversion
Fixed #(issue_no)

#89 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

- [ ] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works
output

### CODE REVIEW

**Review by bislara — APPROVED** [review]
perfect

**Comment by bislara** [comment]
@all-contributors please add vighneshdeepweb for code, doc

**Comment by vighneshdeepweb** [comment]
So is my PR will be counted for hacktoberfest 2020??

**Comment by bislara** [comment]
Yes sure

**Pull request merged**
