### PR TITLE
Added script to download Instagram top media by hashtag

### PR DESCRIPTION
**Pull request by Riken-Shah**
# Description

Added python script that will download top Instagram media from a hashtag.
(Photos and Videos Both)

Fixed #(170)

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
great awesome. Can you add few things?

- [x] Add a readme file having the description of the project, how to setup and run the file. 
- [x] Add screenshots of the output in the readme. 
- [ ] Also add the output files inside the folder.

**Comment by bislara** [comment]
Hey @Riken-Shah  Can u do the 3rd point? ie add at least 2 media files downloaded from this application, so that one can know what is the output file format

**Review by bislara — APPROVED** [review]
Perfect. Good Job

**Comment by bislara** [comment]
@all-contributors please add @Riken-Shah for code, doc

**Comment by Riken-Shah** [comment]
> Perfect. Good Job 

Thanks a lot sir. Learned a lot. 🙏

**Comment by bislara** [comment]
Great. Good to know about it.

Keep Learning 🤟✌

**Pull request merged**
