### PR TITLE
Url shortener using Python and Javascript 

### PR DESCRIPTION
**Pull request by Volku**
I use pyshorteners for Python. For JavaScript, I use tinyurl and bitly

### CODE REVIEW

**Comment by bislara** [comment]
Great. Good job.👍  I would like to suggest a few changes before I merge this PR. 

- [ ] Put the Python and JS code inside different folders
- [ ] Attach Screenshots of your output for python and Js in the PR description 
- [ ] I have added the contributors' list in the readme of the main repo. Please pull and add your name to it. ✌🙌

**Comment by Volku** [comment]
Sorry but I don't know how to pull unless I finish of what you suggest first. So I can't add contributors' list right now

Here's the output
image

image

**Comment by bislara** [comment]
No Worries. I will add your name to the list. ✌

**Review by bislara — APPROVED** [review]
Perfect Code in both python and js

**Pull request merged**
