### PR TITLE
Added 'Image to ASCII converter'

### LINKED ISSUE #163: Image to ASCII converter
## Description
I want to add a python3 script which takes in path to an image as parameter and returns the ascii version of the image

## Technologies and Languages
Language: python3
Libraries: PIL

## Notes
I've already made the project, I think it will be a nice addition to this repo.

### PR DESCRIPTION
**Pull request by volt9801**
# Description
Created a python script that takes in opath to an image as parameter and returns ascii version of the image
Added the following files:
- `converter.py` -> contains the `convert()` function which takes in path of image as parameter and returns ascii version of image
- `README.md` -> contains instructions and requirements for script.

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #163 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Good job bro. Just can you make some changes?

- [ ] Add screenshots of your output in the readme. 
- [ ] In the python file write the code for one test case
- [ ] Mention in the readme how to setup and run the file. 


- [ ]

**Comment by volt9801** [comment]
> Good job bro. Just can you make some changes?
> 
> * [ ]  Add screenshots of your output in the readme.
> * [ ]  In the python file write the code for one test case
> * [ ]  Mention in the readme how to setup and run the file.

@bislara yeah sure man, I'll get back to you after making the changes

**Comment by volt9801** [comment]
@bislara Hey man, I added the screenshot and put a test case in the docstring of the method. Please review it.

**Review by bislara — APPROVED** [review]
Awesome bro, well done.

**Comment by bislara** [comment]
@all-contributors please add volt9801 for code, doc

**Pull request merged**
