### PR TITLE
Added Typing Speed Tester

### LINKED ISSUE #3: Typing Speed Test
## Description
Script to test the Typing Speed of the User

- User must be given a paragraph to see and type the same.
- Take input paragraph from the user.
- Note down the time taken for the user to write the paragraph.
- Show some congratulations message

## Technologies and Language
Open to do in any language and use any technology

### PR DESCRIPTION
**Pull request by iamlordutkarsh**
# Description

Added Typing Speed Tester written in python

Fixed #3 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

##Screenshot
typing_speed_test

### CODE REVIEW

**Comment by bislara** [comment]
Great wonderful. Just I will suggest a few changes.

- [ ] Add a readme inside your project folder and add a description of the project in it. 
- [ ] Add screenshot in the readme

**Comment by iamlordutkarsh** [comment]
Ok Sir I will do

**Review by bislara — APPROVED** [review]
Completed the project

**Comment by bislara** [comment]
@all-contributors please add iamlordutkarsh for code , doc

**Pull request merged**
