### PR TITLE
added invisible cloak folder

### LINKED ISSUE #39: Invisible Cloak
## Description
Write script for the cloak of invisibility which was used by Harry Porter to become invisible. It should make a person invisible in a live webcam. 

## Technologies and Languages

- Python
- Image Processing
- Color detection and segmentation

### PR DESCRIPTION
**Pull request by shubham2704**
# Description
Added the invisible cloak program for the issue #39 

##changes made are
- created a new branch 39-invisible-cloak.
- created a new folder "Invisible Cloak". with the following files:
    - invisble.py
    - screenshot.png
    - README.md
    - requirements.txt

Fixed #39 

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
Great job bro. Well done with the code.

Just one little change.
- [ ] Add the screenshot in the readme as well

**Comment by bislara** [comment]
@shubham2704  you working on this?

**Comment by shubham2704** [comment]
> @shubham2704 you working on this?

@bislara i'am working on this

**Comment by shubham2704** [comment]
@bislara I have made the requested changes.

**Review by bislara — COMMENTED** [review]
Wonderful Job 
Happy Hacking and Learning!

**Comment by bislara** [comment]
@all-contributors please add shubham2704 for code, doc

**Pull request merged**
