### PR TITLE
Javascript Calculator

### LINKED ISSUE #252: Javascript Calculator
## Description
Design a webpage having a calculator in it. It should be able to perform basic operations like addition, subtraction, division, multiplication. There should be a display screen to show the results. Below is an example of the UI, feel free to make it according to you. 

> Put this under the Javascript folder of the repo

image

## Technologies and Languages
HTML, CSS, JS
React(Optional)

## Aditional Work 
Add more functions like factorial, sin, cos, tan, log, ln, square root, square, pi, e, a^b, etc.

### PR DESCRIPTION
**Pull request by devesh-2002**
This is a Javascript Calculator which performs various operations such as Arithmetic, Trigonometric and many more.
JSCalcSS

Fixed #252 

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — CHANGES_REQUESTED** [review]
Well done @devesh-2002. Nicely done.

Could you please add the screenshot of website in readme of the Calculator folder? 
That would make it better. I will merge as soon as this is done.

**Review by bislara — APPROVED** [review]

**Comment by bislara** [comment]
@all-contributors please add @devesh-2002 for code, doc

**Comment by devesh-2002** [comment]
Can you please add the "hacktoberfest-accepted" tag?

**Comment by bislara** [comment]
I am sorry. I forgot to add in this. 
Done now. @devesh-2002

**Pull request merged**
