### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shaansrivastava**

### CODE REVIEW

**Comment by bislara** [comment]
Hey why did you just removed the heart emoji? 😅. Also, whenever you create PR, Write proper description.

**Comment by shaansrivastava** [comment]
> Hey why did you just removed the heart emoji? 😅. Also, whenever you create PR, Write proper description.

Sorry ....... I just missed the description :-)

**Comment by shaansrivastava** [comment]
> Hey why did you just removed the heart emoji? 😅. Also, whenever you create PR, Write proper description.

Can u plzz accept the pull request??

**Comment by bislara** [comment]
Sorry, But I didn't get an answer to my question. 
Why did you just remove the heart emoji in the readme? There is no problem for me in keeping it.

**Pull request closed without merging**
