### PR TITLE
Website-cloner

### LINKED ISSUE #132: Website Cloner
## Description
Given the link of the website, download all the files required for the offline reading, storage, etc.
Web scraping used for extracting data from the websites 

## Technologies and Languages

- Python

Any other technology and language is also welcome.

### PR DESCRIPTION
**Pull request by m4dummies**
# Website cloner

Clones files used in the website 

Fixed #132 

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by m4dummies** [comment]
Hi @bislara is this what you were looking for?

**Comment by bislara** [comment]
Yes, I was looking for something like this. Well, I haven't run the code completely locally. Can you tell whether using the downloaded files, one can load the webpage locally or not?

**Comment by m4dummies** [comment]
Yes one can run the webpage locally, as it saves all the files used in the webpage. The .html file would be saved in: www.websitename.com

**Review by bislara — APPROVED** [review]
Good job. Well done

Keep Learning ✌🙌

**Pull request merged**
