### PR TITLE
Medium article scrapper

### LINKED ISSUE #225: Medium Article Scraper
## Description
Given the link of a medium article, Scrap the complete medium article (and store it in an HTML file if possible ) so that one can see the contents of the article as it is in the medium website, even if one user is not a paid member of Medium and have used the minimum free views. 

## Technologies and Languages
Feel free to use any language and technology

### PR DESCRIPTION
**Pull request by m4dummies**
# Medium article scrapper

The script will save the article content as a pdf. 

Fixed #225 

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by bislara — COMMENTED** [review]
hey, This is not exactly what I wanted. This is same as HTML to pdf conversion. We can have another issue for this. but This issue was specific for Medium Article Scrapper. You need to scrap the website and get everything from that. 

Also, this PR is having files for website cloner as well.

**Comment by m4dummies** [comment]
Yup makes sense. Can you make a issue for this kind of project. I can make a pr for that instead. And are you saying this script should be in the website cloner.

**Comment by bislara** [comment]
Well, you can create an issue and work on that. You have my approval for this HTML to PDF project. Go ahead. 

No I was saying that this PR had code for website cloner as well. Never mind. I will close this PR. 
Also, Do you want to work on this issue as well? or should I unassign u?

**Comment by m4dummies** [comment]
Let me work on the html to pdf conversion first, then i will work on this as i will have to look for a solution. You can unassign me for now.

**Comment by m4dummies** [comment]
I will make a pr for pdf to html and can u assign that to me?

**Pull request closed without merging**
